apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: hippo-azure
spec:
  image: docker.io/ivorysql/ivorysql:ubi8-2.2-1.1-1
  postgresVersion: 15
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: docker.io/ivorysql/pgbackrest:ubi8-2.45-1.1-1
      configuration:
      - secret:
          name: ivyo-azure-creds
      global:
        repo1-path: /pgbackrest/ivory-operator/hippo-azure/repo1
      repos:
      - name: repo1
        azure:
          container: "<YOUR_AZURE_CONTAINER>"
