---
apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  namespace: kuttl-test-delete-namespace
  name: delete-namespace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
---
# Patroni DCS objects are not owned by the PostgresCluster.
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
---
apiVersion: v1
kind: Service
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.ivorysql.org/cluster: delete-namespace
