version: "2"

linters:
  disable-all: true
  enable:
    - contextcheck
    - errchkjson
    - gocritic
    - godot
    - godox
    - goerr113
    - gofumpt
    - gosec
    - nilnil
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - tenv
    - thelper
    - tparallel
    - wastedassign

issues:
  exclude-use-default: false

linters-settings:
  errchkjson:
    check-error-free-encoding: true

  thelper:
    tb:
      begin: true
      first: true
    test:
      begin: true
      first: true
      name: true

run:
  build-tags:
    - envtest