---
apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: delete-with-replica
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
---
# Patroni DCS objects are not owned by the PostgresCluster.
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-with-replica
