apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: hippo-multi-repo
spec:
  image: docker.io/ivorysql/ivorysql:ubi8-2.2-1.1-1
  postgresVersion: 15
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: docker.io/ivorysql/pgbackrest:ubi8-2.45-1.1-1
      configuration:
      - secret:
          name: ivyo-multi-repo-creds
      global:
        repo2-path: /pgbackrest/ivory-operator/hippo-multi-repo/repo2
        repo3-path: /pgbackrest/ivory-operator/hippo-multi-repo/repo3
        repo4-path: /pgbackrest/ivory-operator/hippo-multi-repo/repo4
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        s3:
          bucket: "<YOUR_AWS_S3_BUCKET_NAME>"
          endpoint: "<YOUR_AWS_S3_ENDPOINT>"
          region: "<YOUR_AWS_S3_REGION>"
      - name: repo3
        gcs:
          bucket: "<YOUR_GCS_BUCKET_NAME>"
      - name: repo4
        azure:
          container: "<YOUR_AZURE_CONTAINER>"
