namespace: ivory-operator

secretGenerator:
- name: ivyo-multi-repo-creds
  files:
  - azure.conf
  - gcs.conf
  - gcs-key.json
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
- ivory.yaml
