namespace: ivory-operator

commonLabels:
  app.kubernetes.io/name: ivyo
  # The version below should match the version on the IvoryCluster CRD
  app.kubernetes.io/version: 0.1

bases:
- ../crd
- ../rbac/cluster
- ../manager

images:
- name: ivory-operator
  newName: docker.io/balinor2017/ivory-operator
  newTag: v0.1

patchesJson6902:
- target: { group: apps, version: v1, kind: Deployment, name: ivyo }
  path: selectors.yaml
