apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: ivory
    name: alertmanager
  name: alertmanager
spec:
  type: ClusterIP
  ports:
  - name: alertmanager
    port: 9093
  selector:
    name: alertmanager

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: ivory
    name: grafana
  name: grafana
spec:
  type: ClusterIP
  ports:
  - name: grafana
    port: 3000
  selector:
    name: grafana

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: ivory
    name: prometheus
  name: prometheus
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9090
  selector:
    name: prometheus
