# Red Hat Marketplace requires that bundles work offline. OSBS will fill out
# the "spec.relatedImages" field of the ClusterServiceVersion if it is blank.
#
# https://redhat-connect.gitbook.io/certified-operator-guide/troubleshooting-and-resources/offline-enabled-operators
# https://osbs.readthedocs.io/en/latest/users.html#pinning-pullspecs-for-related-images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivyo
spec:
  template:
    spec:
      containers:
        - name: operator
          image: docker.io/balinor2017/ivory-operator@sha256:<update_operator_SHA_value>
          env:
            - { name: RELATED_IMAGE_PGADMIN, value: 'docker.io/dpage/pgadmin4@sha256:<update_pgadmin_SHA_value>' }
            - { name: RELATED_IMAGE_PGBACKREST, value: 'docker.io/balinor2017/highgo-pgbackrest@sha256:<update_pgbackrest_SHA_value>' }
            - { name: RELATED_IMAGE_PGBOUNCER,  value: 'docker.io/bitnami/pgbouncer@sha256:<update_pgbouncer_SHA_value>' }
            - { name: RELATED_IMAGE_PGEXPORTER, value: 'docker.io/bitnami/postgres-exporter@sha256:<update_exporter_SHA_value>' }

            - { name: RELATED_IMAGE_IVORY_15, value: 'docker.io/balinor2017/highgo-ivory@sha256:<update_postgres14_SHA_value>' }