---
# Wait for switchover to finish. A former replica should now be the primary.
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-switchover-with-timestamp
    ivory-operator.ivorysql.org/data: ivory
    ivory-operator.ivorysql.org/role: master
    testing/role-before: replica
---
# The former primary should now be a replica.
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: delete-switchover-with-timestamp
    ivory-operator.ivorysql.org/data: ivory
    ivory-operator.ivorysql.org/role: replica
    testing/role-before: master
---
# All instances should be healthy.
apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: delete-switchover-with-timestamp
status:
  instances:
    - name: instance1
      replicas: 2
      readyReplicas: 2
      updatedReplicas: 2
