---
# Wait for the clone cluster to come online.
apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: clone-one
status:
  instances:
    - name: '00'
      replicas: 1
      readyReplicas: 1
      updatedReplicas: 1
