---
# Annotate the cluster with the timestamp at which PostgreSQL last started.
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      PRIMARY=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            ivory-operator.ivorysql.org/cluster=original,
            ivory-operator.ivorysql.org/role=master'
      )
      START=$(
        kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" \
          -- psql -d postgres -qAt --command 'SELECT pg_postmaster_start_time()'
      )
      kubectl annotate --namespace "${NAMESPACE}" ivorycluster/original \
        "testing/start-before=${START}"
