---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      BEFORE=$(
        kubectl get --namespace "${NAMESPACE}" ivorycluster/original \
          --output 'go-template={{ index .metadata.annotations "testing/start-before" }}'
      )
      PRIMARY=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            ivory-operator.ivorysql.org/cluster=original,
            ivory-operator.ivorysql.org/role=master'
      )

      # Wait for PostgreSQL to restart.
      while true; do
        START=$(
          kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" \
            -- psql -d postgres -qAt --command 'SELECT pg_postmaster_start_time()'
        )
        if [ "${START}" ] && [ "${START}" != "${BEFORE}" ]; then break; else sleep 1; fi
      done
      echo "${START} != ${BEFORE}"

      # Reset counters in the "pg_stat_archiver" view.
      kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" \
        -- psql -d postgres -qb --command "SELECT pg_stat_reset_shared('archiver')"
