---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivory-operator
  labels:
    ivory-operator.ivorysql.org/control-plane: ivory-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ivory-operator
subjects:
- kind: ServiceAccount
  name: ivyo
