---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivory-operator-upgrade
  labels:
    ivory-operator.ivorysql.org/control-plane: ivory-operator-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ivory-operator-upgrade
subjects:
- kind: ServiceAccount
  name: ivory-operator-upgrade
