namespace: ivory-operator

commonLabels:
  ivory-operator.highgo.com/control-plane: ivory-operator

bases:
- ../crd
- ../rbac/namespace
- ../manager

patches:
- path: manager-target.yaml

images:
- name: postgres-operator
  newName: docker.io/balinor2017/ivory-operator
  newTag: v0.1
