namespace: ivory-operator

commonLabels:
  ivory-operator.ivorysql.org/control-plane: ivory-operator

bases:
- ../crd
- ../rbac/namespace
- ../manager

patches:
- path: manager-target.yaml

images:
- name: ivory-operator
  newName: docker.io/balinor2017/ivory-operator
  newTag: v0.4
