apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: cluster-start
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: cluster-start
    ivory-operator.ivorysql.org/pgbackrest-backup: replica-create
status:
  succeeded: 1
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-start-primary
