---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ivory-operator-upgrade
  labels:
    ivory-operator.ivorysql.org/control-plane: ivory-operator-upgrade
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ivory-operator.ivorysql.org
  resources:
  - pgupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ivory-operator.ivorysql.org
  resources:
  - pgupgrades/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - ivory-operator.ivorysql.org
  resources:
  - pgupgrades/status
  verbs:
  - get
  - patch
- apiGroups:
  - ivory-operator.ivorysql.org
  resources:
  - ivorysclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ivory-operator.ivorysql.org
  resources:
  - ivorysclusters/status
  verbs:
  - patch
