---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ivory-operator-upgrade
  labels:
    ivory-operator.ivorysql.org/control-plane: ivory-operator-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ivory-operator-upgrade
subjects:
- kind: ServiceAccount
  name: ivory-operator-upgrade
