# We know that the PVC sizes have change so now we can check that they have been
# updated to have the expected size
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: resize-volume-up
    ivory-operator.ivorysql.org/instance-set: instance1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: resize-volume-up
    ivory-operator.ivorysql.org/data: pgbackrest
    ivory-operator.ivorysql.org/pgbackrest-repo: repo1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
