apiVersion: v1
kind: Event
type: Warning
involvedObject:
  apiVersion: ivory-operator.ivorysql.org/v1beta1
  kind: IvoryCluster
  name: resize-volume-down
reason: PersistentVolumeError
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: resize-volume-down
    ivory-operator.ivorysql.org/instance-set: instance1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: resize-volume-down
    ivory-operator.ivorysql.org/data: pgbackrest
    ivory-operator.ivorysql.org/pgbackrest-repo: repo1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
