---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Label instance pods with their current role.
  - script: |
      kubectl label --namespace="${NAMESPACE}" pods \
        --selector='ivory-operator.ivorysql.org/role=master' \
        'testing/role-before=master'
  - script: |
      kubectl label --namespace="${NAMESPACE}" pods \
        --selector='ivory-operator.ivorysql.org/role=replica' \
        'testing/role-before=replica'
