apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: scaledown1
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: scaledown1
    ivory-operator.ivorysql.org/instance-set: instance1
    ivory-operator.ivorysql.org/role: master
    testing/role-before: master
status:
  phase: Running
