apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    # Assumes the cluster only has a single replica
    NEW_REPLICA=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            ivory-operator.ivorysql.org/cluster=init-pgbackrest,
            ivory-operator.ivorysql.org/role=replica'
      )

    LIST=$(
    kubectl exec --namespace "${NAMESPACE}" "${NEW_REPLICA}" -- \
      ls /pgdata/pg${KUTTL_PG_VERSION}/
    )

    contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }
    {
      !(contains "${LIST}" 'recovery.signal')
    } || {
      echo >&2 'Signal file(s) found'
      echo "${LIST}"
      exit 1
    }
